---
  jenkins_prefer_lts: false
  packageName: jenkins
  packageLog: Jenkins
  jenkins_admin_username: admin
  jenkins_admin_password: vorobey
  jenkins_repo_url: deb https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }} binary/
  jenkins_repo_key_url: https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }}/jenkins.io.key