---
  - import_tasks: nginxInstall.yml
    tags:
      - deploy
      - install_nginx

  - import_tasks: nginxStart.yml
    tags:
      - deploy
      - start_nginx

  - import_tasks: nginxConfig.yml
    tags:
      - deploy
      - config_nginx

  - import_tasks: nginxRemove.yml
    tags:
      - remove_nginx
      - erase

  - import_tasks: nginxRestart.yml
    tags:
      - restart_nginx

  - import_tasks: nginxStop.yml
    tags:
      - stop_nginx
