---
  -  name: "{{ packageLog }} Install"
     package:
       name: "{{ packageName }}"
       state: latest
       update_cache: yes
    # when: packageName not in ansible_facts.packages
     tags:
       - install_nginx
       - deploy
